# -*- coding: utf-8 -*-
"""Project1yz4336.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xN7AS8cy7Ar30Wvx30fP6hDjZCCGVtGi

# STAT5342 Project 1 
**By Yiming Zhu yz4336**

# Introduction of dataset
For this project, I use the History of Philosophy dataset. This data site is about the sentences given by different philosophers from different schools. In this dataset, we can exam the pattern, the word choice of differet philosopher. 

Source: https://www.kaggle.com/datasets/kouroshalizadeh/history-of-philosophy?resource=download

#Question1: Among *analytic* and *aristotle*, philosophers from which school prefer long sentences

I wonder if the different teaching methods in different schools will affect the language models of philosophers. For example, some colleges choose textbooks, so philosophers in that college tend to choose longer philosophical sentences. To investigate this question, I choose two schools that I am interested most, analytic and aristotle. 

#Method
To investigate this question, I choose two schools that I am interested most, analytic and aristotle. Firstly, I wrangle the data so that it has two column: *school* and *sentence_length*. Here, school only contains records of analytic and aristotle. 

Then I calculted *Pearson's chi-squared test* of the sentence length across schools to explore whether there were significant differences. Pearson's chi-squared test is a statistical test used to determine if there is a significant difference between the observed and expected frequencies in one or more categorical variables. It is commonly used to determine if there is a relationship between two categorical variables. The test calculates the chi-squared statistic, which is a measure of the difference between the observed and expected frequencies, and compares it to a critical value from the chi-squared distribution to determine if the difference is significant. The result of the test can be used to accept or reject the null hypothesis that the variables are independent.
"""

from google.colab import drive
drive.mount('/content/drive') 
import pandas as pd

philosophy=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/STAT5243/philosophy_data.csv')

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/STAT5243/philosophy_data.csv')
df.head(10)

df2=df[df['school'].isin(['analytic','aristotle'])].reset_index() 
df3=df2[['school','sentence_length']]

from scipy.stats import chisquare
chisquare(df3['school'].value_counts())

"""In our analysis, the p-value of the chi-squared test is less than 0.05. Hence, there is no significant difference of the sentence length between *analytic* and *aristotle*.

#Question2: Which philosopher's sentence has the longest average sentence length

I'm curious whether different philosophers have significant differences in the length of sentences. 

#Method
To explore this question, I group the data by the author and calculate the average sentence length for each philosopher and compared them.
"""

df5 = df.groupby('author')['sentence_length'].aggregate(['mean'])
df5

"""Based on the DataFrame above, we can see that different authors have different avgerage sentence length. Wittgenstein has average sentence length of 84.883772 words, while Descartes	has average sentence length of 247.381625. So different authors have very different avgerage sentence length.

#Conclusion
Based on our anaysis, there is no significant difference of the sentence length between *analytic* and *aristotle*. In addition, different authors have very different avgerage sentence length.
"""